// scripts/marketplace-seed/catalog/animeCharacters.ts
// anime character metadata for marketplace template seeds

import type { FolderMeta } from '../types'

export const ANIME_CHARACTERS_TEMPLATE_META = {
  'anime-protagonists': {
    title: 'Anime protagonists',
    category: 'anime',
    description:
      'Lead and central characters from influential anime and manga series.',
    tags: ['anime', 'characters', 'protagonists'],
    labels: true,
    itemLabels: {
      '01-tanjiro-kamado.png': 'Tanjiro Kamado',
      '02-ichigo-kurosaki.png': 'Ichigo Kurosaki',
      '03-monkey-d-luffy.png': 'Monkey D. Luffy',
      '04-sailor-moon.jpg': 'Sailor Moon',
      '05-izuku-midoriya.png': 'Izuku Midoriya',
      '06-goku.png': 'Goku',
      '07-naruto-uzumaki.png': 'Naruto Uzumaki',
      '08-eren-yeager.jpg': 'Eren Yeager',
      '09-edward-elric.jpg': 'Edward Elric',
      '10-light-yagami.png': 'Light Yagami',
      '11-ash-ketchum.png': 'Ash Ketchum',
      '12-gon-freecss.jpg': 'Gon Freecss',
      '13-spike-spiegel.png': 'Spike Spiegel',
      '14-l.png': 'L',
      '15-yusuke-urameshi.png': 'Yusuke Urameshi',
      '16-shinji-ikari.png': 'Shinji Ikari',
      '17-kenshin-himura.png': 'Kenshin Himura',
      '18-vash-the-stampede.png': 'Vash the Stampede',
      '19-mob.png': 'Mob',
      '20-lelouch-lamperouge.png': 'Lelouch Lamperouge',
      '21-saitama.jpg': 'Saitama',
      '22-jotaro-kujo.png': 'Jotaro Kujo',
      '23-guts.png': 'Guts',
      '24-inuyasha.png': 'Inuyasha',
      '25-frieren.png': 'Frieren',
      '26-ryuko-matoi.png': 'Ryuko Matoi',
      '27-yuji-itadori.png': 'Yuji Itadori',
      '28-denji.png': 'Denji',
      '29-anya-forger.png': 'Anya Forger',
      '30-thorfinn.png': 'Thorfinn',
      '31-natsu-dragneel.png': 'Natsu Dragneel',
      '32-asta.png': 'Asta',
      '33-yugi-muto.jpg': 'Yugi Muto',
      '34-kenshiro.jpg': 'Kenshiro',
      '35-astro-boy.jpg': 'Astro Boy',
      '36-motoko-kusanagi.jpg': 'Motoko Kusanagi',
      '37-alucard.jpg': 'Alucard',
      '38-kirito.png': 'Kirito',
      '39-simon.jpg': 'Simon',
      '40-haruhi-suzumiya.png': 'Haruhi Suzumiya',
      '41-koyomi-araragi.png': 'Koyomi Araragi',
      '42-madoka-kaname.jpg': 'Madoka Kaname',
      '43-sakura-kinomoto.png': 'Sakura Kinomoto',
      '44-tohru-honda.png': 'Tohru Honda',
      '45-violet-evergarden.png': 'Violet Evergarden',
      '46-rintaro-okabe.png': 'Rintaro Okabe',
      '47-giorno-giovanna.png': 'Giorno Giovanna',
      '48-josuke-higashikata.jpg': 'Josuke Higashikata',
      '49-jonathan-joestar.png': 'Jonathan Joestar',
      '50-senku-ishigami.png': 'Senku Ishigami',
      '51-soma-yukihira.jpg': 'Soma Yukihira',
      '52-shoyo-hinata.png': 'Shoyo Hinata',
      '53-tetsuya-kuroko.png': 'Tetsuya Kuroko',
      '54-ippo-makunouchi.jpg': 'Ippo Makunouchi',
      '55-joe-yabuki.jpg': 'Joe Yabuki',
      '56-gintoki-sakata.png': 'Gintoki Sakata',
      '57-toriko.png': 'Toriko',
      '58-eikichi-onizuka.png': 'Eikichi Onizuka',
      '59-lupin-iii.jpg': 'Lupin III',
      '60-conan-edogawa.png': 'Conan Edogawa',
      '61-taichi-yagami.png': 'Taichi Yagami',
      '62-kaneki-ken.png': 'Kaneki Ken',
      '63-emma.png': 'Emma',
      '64-maka-albarn.png': 'Maka Albarn',
      '65-atsushi-nakajima.png': 'Atsushi Nakajima',
      '66-rimuru-tempest.png': 'Rimuru Tempest',
      '67-subaru-natsuki.png': 'Subaru Natsuki',
      '68-kazuma-satou.png': 'Kazuma Satou',
      '69-naofumi-iwatani.png': 'Naofumi Iwatani',
      '70-ainz-ooal-gown.png': 'Ainz Ooal Gown',
      '71-tanya-degurechaff.png': 'Tanya Degurechaff',
      '72-kaguya-shinomiya.png': 'Kaguya Shinomiya',
      '73-hachiman-hikigaya.png': 'Hachiman Hikigaya',
      '74-tomoya-okazaki.png': 'Tomoya Okazaki',
      '75-shirou-emiya.png': 'Shirou Emiya',
      '76-saber.png': 'Saber',
      '77-shana.png': 'Shana',
      '78-yato.png': 'Yato',
      '79-yona.png': 'Yona',
      '80-shirayuki.png': 'Shirayuki',
      '81-kaiman.png': 'Kaiman',
      '82-rudeus-greyrat.png': 'Rudeus Greyrat',
      '83-chihiro-ogino.png': 'Chihiro Ogino',
      '84-nausicaa.png': 'Nausicaä',
      '85-kiki.png': 'Kiki',
      '86-ashitaka.png': 'Ashitaka',
      '87-bojji.png': 'Bojji',
      '88-maomao.png': 'Maomao',
      '89-laios-touden.png': 'Laios Touden',
      '90-kafka-hibino.png': 'Kafka Hibino',
      '91-mash-burnedead.jpg': 'Mash Burnedead',
      '92-nagisa-shiota.png': 'Nagisa Shiota',
      '93-kusuo-saiki.png': 'Kusuo Saiki',
      '94-takemichi-hanagaki.png': 'Takemichi Hanagaki',
      '95-boruto-uzumaki.jpg': 'Boruto Uzumaki',
      '96-meliodas.png': 'Meliodas',
      '97-holo.jpg': 'Holo',
      '98-kraft-lawrence.png': 'Kraft Lawrence',
      '99-riko.png': 'Riko',
      '100-akko-kagari.png': 'Akko Kagari',
    },
  },
} satisfies Record<string, FolderMeta>
