// scripts/marketplace-seed/catalog/animeSeries.ts
// anime series metadata for marketplace template seeds

import type { FolderMeta } from '../types'

export const ANIME_SERIES_TEMPLATE_META = {
  'manga-series': {
    title: 'Manga series',
    category: 'anime',
    description:
      'Popular and influential manga series across shonen, seinen, sports, shojo, josei, comedy, romance, and modern hits.',
    tags: ['manga', 'anime', 'comics'],
    labels: true,
    itemLabels: {
      '01-jujutsu-kaisen.jpg': 'Jujutsu Kaisen',
      '02-naruto.jpg': 'Naruto',
      '03-dragon-ball.jpg': 'Dragon Ball',
      '04-attack-on-titan.jpg': 'Attack on Titan',
      '05-one-piece.jpg': 'One Piece',
      '06-bleach.jpg': 'Bleach',
      '07-my-hero-academia.jpg': 'My Hero Academia',
      '08-demon-slayer.jpg': 'Demon Slayer',
      '09-fullmetal-alchemist.jpg': 'Fullmetal Alchemist',
      '10-hunter-x-hunter.jpg': 'Hunter x Hunter',
      '11-jojo-s-bizarre-adventure.jpg': "JoJo's Bizarre Adventure",
      '12-chainsaw-man.jpg': 'Chainsaw Man',
      '13-death-note.jpg': 'Death Note',
      '14-tokyo-ghoul.jpg': 'Tokyo Ghoul',
      '15-berserk.jpg': 'Berserk',
      '16-sailor-moon.jpg': 'Sailor Moon',
      '17-fruits-basket.jpg': 'Fruits Basket',
      '18-slam-dunk.jpg': 'Slam Dunk',
      '19-blue-lock.jpg': 'Blue Lock',
      '20-spy-x-family.jpg': 'Spy x Family',
      '21-haikyu.jpg': 'Haikyu!!',
      '22-vagabond.jpg': 'Vagabond',
      '23-vinland-saga.jpg': 'Vinland Saga',
      '24-monster.jpg': 'Monster',
      '25-nana.jpg': 'Nana',
      '26-black-clover.jpg': 'Black Clover',
      '27-akira.jpg': 'Akira',
      '28-gintama.jpg': 'Gintama',
      '29-mob-psycho-100.jpg': 'Mob Psycho 100',
      '30-yuyu-hakusho.jpg': 'YuYu Hakusho',
      '31-one-punch-man.jpg': 'One-Punch Man',
      '32-kingdom.jpg': 'Kingdom',
      '33-fairy-tail.jpg': 'Fairy Tail',
      '34-the-seven-deadly-sins.jpg': 'The Seven Deadly Sins',
      '35-rurouni-kenshin.jpg': 'Rurouni Kenshin',
      '36-inuyasha.jpg': 'Inuyasha',
      '37-ranma-1-2.jpg': 'Ranma 1/2',
      '38-case-closed.jpg': 'Case Closed',
      '39-yu-gi-oh.jpg': 'Yu-Gi-Oh!',
      '40-dr-stone.jpg': 'Dr. Stone',
      '41-fire-force.jpg': 'Fire Force',
      '42-soul-eater.jpg': 'Soul Eater',
      '43-d-gray-man.jpg': 'D.Gray-man',
      '44-reborn.jpg': 'Reborn!',
      '45-the-promised-neverland.jpg': 'The Promised Neverland',
      '46-made-in-abyss.jpg': 'Made in Abyss',
      '47-kaguya-sama-love-is-war.jpg': 'Kaguya-sama: Love Is War',
      '48-oshi-no-ko.jpg': 'Oshi no Ko',
      '49-frieren-beyond-journey-s-end.jpg': "Frieren: Beyond Journey's End",
      '50-dandadan.jpg': 'Dandadan',
      '51-delicious-in-dungeon.jpg': 'Delicious in Dungeon',
      '52-komi-can-t-communicate.jpg': "Komi Can't Communicate",
      '53-yotsuba-and.jpg': 'Yotsuba&!',
      '54-azumanga-daioh.jpg': 'Azumanga Daioh',
      '55-nichijou.jpg': 'Nichijou',
      '56-great-teacher-onizuka.jpg': 'Great Teacher Onizuka',
      '57-initial-d.jpg': 'Initial D',
      '58-hajime-no-ippo.jpg': 'Hajime no Ippo',
      '59-kuroko-s-basketball.jpg': "Kuroko's Basketball",
      '60-eyeshield-21.jpg': 'Eyeshield 21',
      '61-chihayafuru.jpg': 'Chihayafuru',
      '62-ao-haru-ride.jpg': 'Ao Haru Ride',
      '63-ouran-high-school-host-club.jpg': 'Ouran High School Host Club',
      '64-skip-beat.jpg': 'Skip Beat!',
      '65-kimi-ni-todoke.jpg': 'Kimi ni Todoke',
      '66-boys-over-flowers.jpg': 'Boys Over Flowers',
      '67-cardcaptor-sakura.jpg': 'Cardcaptor Sakura',
      '68-a-silent-voice.jpg': 'A Silent Voice',
      '69-your-lie-in-april.jpg': 'Your Lie in April',
      '70-20th-century-boys.jpg': '20th Century Boys',
      '71-pluto.jpg': 'Pluto',
      '72-dorohedoro.jpg': 'Dorohedoro',
      '73-parasyte.jpg': 'Parasyte',
      '74-golden-kamuy.jpg': 'Golden Kamuy',
      '75-claymore.jpg': 'Claymore',
      '76-hellsing.jpg': 'Hellsing',
      '77-trigun.jpg': 'Trigun',
      '78-nausicaa-of-the-valley-of-the-wind.jpg':
        'Nausicaä of the Valley of the Wind',
      '79-lone-wolf-and-cub.jpg': 'Lone Wolf and Cub',
      '80-the-rose-of-versailles.jpg': 'The Rose of Versailles',
      '81-astro-boy.jpg': 'Astro Boy',
    },
  },
  'studio-trigger-anime': {
    title: 'Studio Trigger anime',
    category: 'anime',
    description:
      'TV series, films, specials, music videos, shorts, and PV projects from Studio Trigger.',
    tags: ['anime', 'studio trigger', 'animation'],
    labels: true,
    itemLabels: {
      '01-inferno-cop.png': 'Inferno Cop',
      '02-inferno-cop-fact-files.jpg': 'Inferno Cop: Fact Files',
      '03-yonhyakunijuu-renpai-girl.jpg': 'Yonhyakunijuu Renpai Girl',
      '04-little-witch-academia.jpg': 'Little Witch Academia',
      '05-turning-girls.jpg': 'Turning Girls',
      '06-kill-la-kill.png': 'Kill la Kill',
      '07-bishoujo-mobage-mobami-chan.png': 'Bishoujo Mobage: Mobami-chan',
      '08-kill-la-kill-goodbye-again.jpg': 'Kill la Kill: GOODBYE AGAIN',
      '09-hacka-doll.jpg': 'Hacka Doll',
      '10-when-supernatural-battles-became-commonplace.jpg':
        'When Supernatural Battles Became Commonplace',
      '11-yume-no-ukiyo-ni-saitemina.png': 'Yume no Ukiyo ni Saitemina',
      '12-ninja-slayer-from-animation.jpg': 'Ninja Slayer from Animation',
      '13-inferno-cop-specials.jpg': 'Inferno Cop Specials',
      '14-change-our-mirai.png': 'Change Our Mirai!',
      '15-hackadoll-the-animation.jpg': 'Hackadoll the Animation',
      '16-little-witch-academia-the-enchanted-parade.jpg':
        'Little Witch Academia: The Enchanted Parade',
      '17-space-patrol-luluco.jpg': 'Space Patrol Luluco',
      '18-kiznaiver.jpg': 'Kiznaiver',
      '19-trigger-chan.jpg': 'Trigger-chan',
      '20-little-witch-academia-tv.jpg': 'Little Witch Academia (TV)',
      '21-darling-in-the-franxx.png': 'Darling in the Franxx',
      '22-ssss-gridman.jpg': 'SSSS.Gridman',
      '23-promare-galo.png': 'Promare: Galo',
      '24-promare-lio.jpg': 'Promare: Lio',
      '25-promare.png': 'Promare',
      '26-delicious-in-dungeon-cm.jpg': 'Delicious in Dungeon CM',
      '27-crescent-rise.jpg': 'Crescent Rise',
      '28-bna-brand-new-animal.jpg': 'BNA: Brand New Animal',
      '29-azur-lane-anime-pvs.png': 'Azur Lane Anime PVs',
      '30-ssss-dynazenon.png': 'SSSS.Dynazenon',
      '31-star-wars-visions.jpg': 'Star Wars: Visions',
      '32-cyberpunk-edgerunners.jpg': 'Cyberpunk: Edgerunners',
      '33-ssss-gridman-movie.jpg': 'SSSS.Gridman Movie',
      '34-ssss-dynazenon-grand-episode.jpg': 'SSSS.Dynazenon Grand Episode',
      '35-gridman-universe.png': 'Gridman Universe',
      '36-delicious-in-dungeon.jpg': 'Delicious in Dungeon',
      '37-chocolat-cadabra.jpg': 'Chocolat Cadabra',
      '38-transformers-40th-anniversary-special-movie.jpg':
        'Transformers 40th Anniversary Special Movie',
      '39-new-panty-and-stocking-with-garterbelt.jpg':
        'New Panty & Stocking with Garterbelt',
      '40-star-wars-visions-volume-3.jpg': 'Star Wars: Visions Volume 3',
      '41-the-lenticulars.jpg': 'The Lenticulars',
    },
  },
  'gundam-series': {
    title: 'Gundam series',
    category: 'anime',
    description:
      'Major Gundam TV series, films, OVAs, SD entries, and Build-era projects.',
    tags: ['anime', 'gundam', 'mecha'],
    labels: true,
    itemLabels: {
      '01-mobile-suit-gundam.jpg': 'Mobile Suit Gundam',
      '02-mobile-suit-gundam-i.jpg': 'Mobile Suit Gundam I',
      '03-soldiers-of-sorrow.jpg': 'Soldiers of Sorrow',
      '04-encounters-in-space.jpg': 'Encounters in Space',
      '05-zeta-gundam.jpg': 'Zeta Gundam',
      '06-gundam-zz.png': 'Gundam ZZ',
      '07-char-s-counterattack.png': "Char's Counterattack",
      '08-war-in-the-pocket.png': 'War in the Pocket',
      '09-stardust-memory.jpg': 'Stardust Memory',
      '10-the-afterglow-of-zeon.jpg': 'The Afterglow of Zeon',
      '11-gundam-f91.png': 'Gundam F91',
      '12-victory-gundam.jpg': 'Victory Gundam',
      '13-g-gundam.png': 'G Gundam',
      '14-gundam-wing.png': 'Gundam Wing',
      '15-the-08th-ms-team.jpg': 'The 08th MS Team',
      '16-after-war-gundam-x.png': 'After War Gundam X',
      '17-endless-waltz.png': 'Endless Waltz',
      '18-turn-a-gundam.jpg': 'Turn A Gundam',
      '19-gundam-evolve.jpg': 'Gundam Evolve',
      '20-gundam-seed.jpg': 'Gundam SEED',
      '21-sd-gundam-force.jpg': 'SD Gundam Force',
      '22-seed-destiny.jpg': 'SEED Destiny',
      '23-ms-igloo-the-hidden-one-year-war.jpg':
        'MS IGLOO: The Hidden One Year War',
      '24-ms-igloo-apocalypse-0079.jpg': 'MS IGLOO: Apocalypse 0079',
      '25-ms-igloo-2-gravity-of-the-battlefront.jpg':
        'MS IGLOO 2: Gravity of the Battlefront',
      '26-seed-c-e-73-stargazer.jpg': 'SEED C.E.73: Stargazer',
      '27-gundam-00.jpg': 'Gundam 00',
      '28-gundam-00-second-season.png': 'Gundam 00 Second Season',
      '29-a-wakening-of-the-trailblazer.png': 'A Wakening of the Trailblazer',
      '30-gundam-unicorn.jpg': 'Gundam Unicorn',
      '31-gundam-age.jpg': 'Gundam AGE',
      '32-gundam-age-memory-of-eden.jpg': 'Gundam AGE: Memory of Eden',
      '33-gundam-build-fighters.jpg': 'Gundam Build Fighters',
      '34-reconguista-in-g.jpg': 'Reconguista in G',
      '35-gundam-build-fighters-try.png': 'Gundam Build Fighters Try',
      '36-the-origin.png': 'The Origin',
      '37-iron-blooded-orphans.jpg': 'Iron-Blooded Orphans',
      '38-gundam-thunderbolt.jpg': 'Gundam Thunderbolt',
      '39-iron-blooded-orphans-2.jpg': 'Iron-Blooded Orphans 2',
      '40-build-fighters-battlogue.jpg': 'Build Fighters: Battlogue',
      '41-twilight-axis.png': 'Twilight AXIS',
      '42-gundam-build-divers.jpg': 'Gundam Build Divers',
      '43-gundam-narrative.jpg': 'Gundam Narrative',
      '44-build-divers-re-rise.png': 'Build Divers Re:RISE',
      '45-sd-gundam-world-sangoku-soketsuden.jpg':
        'SD Gundam World Sangoku Soketsuden',
      '46-hathaway.jpg': 'Hathaway',
      '47-build-divers-re-rise-2nd-season.jpg':
        'Build Divers Re:RISE 2nd Season',
      '48-build-divers-battlogue.jpg': 'Build Divers Battlogue',
      '49-sd-gundam-world-heroes.jpg': 'SD Gundam World Heroes',
      '50-gundam-breaker-battlogue.png': 'Gundam Breaker Battlogue',
      '51-cucuruz-doan-s-island.jpg': "Cucuruz Doan's Island",
      '52-the-witch-from-mercury-prologue.png':
        'The Witch from Mercury: Prologue',
      '53-the-witch-from-mercury.png': 'The Witch from Mercury',
      '54-the-witch-from-mercury-season-2.jpg':
        'The Witch from Mercury Season 2',
      '55-gundam-build-metaverse.jpg': 'Gundam Build Metaverse',
      '56-seed-freedom.jpg': 'SEED Freedom',
      '57-requiem-for-vengeance.jpg': 'Requiem for Vengeance',
      '58-gquuuuuux.jpg': 'GQuuuuuuX',
    },
  },
  'one-piece-arcs': {
    title: 'One Piece story arcs',
    category: 'anime',
    description:
      'Story arcs from One Piece, sourced from One Piece Wiki arc artwork.',
    tags: ['anime', 'one piece', 'arcs'],
    labels: true,
  },
} satisfies Record<string, FolderMeta>
