// scripts/marketplace-seed/catalog/books.ts
// book example metadata for marketplace template seeds

import type { FolderMeta } from '../types'

export const BOOKS_TEMPLATE_META = {
  'classic-novels': {
    title: 'Classic novels',
    category: 'books',
    description:
      'Canonical novels and epics often found on school shelves and all-time lists.',
    tags: ['books', 'classics', 'literature'],
    labels: true,
    itemLabels: {
      '01-moby-dick.jpg': 'Moby-Dick',
      '02-frankenstein.jpg': 'Frankenstein',
      '03-wuthering-heights.jpg': 'Wuthering Heights',
      '04-jane-eyre.jpg': 'Jane Eyre',
      '05-great-expectations.jpg': 'Great Expectations',
      '06-the-picture-of-dorian-gray.jpg': 'The Picture of Dorian Gray',
      '07-pride-and-prejudice.jpg': 'Pride and Prejudice',
      '08-dracula.jpg': 'Dracula',
      '09-alice-s-adventures-in-wonderland.jpg':
        "Alice's Adventures in Wonderland",
      '10-anna-karenina.jpg': 'Anna Karenina',
      '11-adventures-of-huckleberry-finn.jpg': 'Adventures of Huckleberry Finn',
      '12-war-and-peace.jpg': 'War and Peace',
      '13-don-quixote.jpg': 'Don Quixote',
      '14-the-count-of-monte-cristo.jpg': 'The Count of Monte Cristo',
      '15-crime-and-punishment.jpg': 'Crime and Punishment',
      '16-les-miserables.jpg': 'Les Misérables',
      '17-the-great-gatsby.jpg': 'The Great Gatsby',
      '18-to-kill-a-mockingbird.jpg': 'To Kill a Mockingbird',
      '19-the-brothers-karamazov.jpg': 'The Brothers Karamazov',
      '20-nineteen-eighty-four.jpg': 'Nineteen Eighty-Four',
      '21-the-catcher-in-the-rye.jpg': 'The Catcher in the Rye',
      '22-fahrenheit-451.jpg': 'Fahrenheit 451',
      '23-brave-new-world.jpg': 'Brave New World',
      '24-the-grapes-of-wrath.jpg': 'The Grapes of Wrath',
      '25-lord-of-the-flies.jpg': 'Lord of the Flies',
      '26-the-hobbit.jpg': 'The Hobbit',
      '27-the-odyssey.jpg': 'The Odyssey',
      '28-the-lord-of-the-rings.jpg': 'The Lord of the Rings',
      '29-the-iliad.jpg': 'The Iliad',
      '30-ulysses.jpg': 'Ulysses',
    },
  },
  'fantasy-book-series': {
    title: 'Fantasy book series',
    category: 'books',
    description:
      'Popular fantasy series spanning epic, portal, grimdark, and modern fantasy.',
    tags: ['books', 'fantasy', 'series'],
    labels: true,
    itemLabels: {
      '01-discworld.jpg': 'Discworld',
      '02-mistborn.jpg': 'Mistborn',
      '03-a-song-of-ice-and-fire.jpg': 'A Song of Ice and Fire',
      '04-the-wheel-of-time.jpg': 'The Wheel of Time',
      '05-the-stormlight-archive.jpg': 'The Stormlight Archive',
      '06-the-kingkiller-chronicle.jpg': 'The Kingkiller Chronicle',
      '07-the-lord-of-the-rings.jpg': 'The Lord of the Rings',
      '08-the-witcher.jpg': 'The Witcher',
      '09-earthsea.jpg': 'Earthsea',
      '10-the-chronicles-of-narnia.jpg': 'The Chronicles of Narnia',
      '11-his-dark-materials.jpg': 'His Dark Materials',
      '12-the-inheritance-cycle.jpg': 'The Inheritance Cycle',
      '13-the-broken-earth.jpg': 'The Broken Earth',
      '14-malazan-book-of-the-fallen.jpg': 'Malazan Book of the Fallen',
      '15-the-first-law.jpg': 'The First Law',
      '16-the-farseer-trilogy.jpg': 'The Farseer Trilogy',
      '17-the-belgariad.jpg': 'The Belgariad',
      '18-the-magicians.jpg': 'The Magicians',
      '19-the-poppy-war.jpg': 'The Poppy War',
      '20-the-dresden-files.jpg': 'The Dresden Files',
      '21-redwall.jpg': 'Redwall',
      '22-percy-jackson.jpg': 'Percy Jackson',
      '23-artemis-fowl.jpg': 'Artemis Fowl',
      '24-the-dark-tower.jpg': 'The Dark Tower',
      '25-the-black-company.jpg': 'The Black Company',
      '26-the-chronicles-of-amber.jpg': 'The Chronicles of Amber',
      '27-shannara.jpg': 'Shannara',
      '28-dragonriders-of-pern.jpg': 'Dragonriders of Pern',
      '29-the-riftwar-cycle.jpg': 'The Riftwar Cycle',
      '30-the-dark-is-rising.jpg': 'The Dark Is Rising',
      '31-the-chronicles-of-prydain.jpg': 'The Chronicles of Prydain',
      '32-elric.jpg': 'Elric',
      '33-conan.jpg': 'Conan',
      '34-memory-sorrow-and-thorn.jpg': 'Memory, Sorrow, and Thorn',
      '35-the-sword-of-truth.jpg': 'The Sword of Truth',
      '36-the-runelords.jpg': 'The Runelords',
      '37-the-deed-of-paksenarrion.jpg': 'The Deed of Paksenarrion',
      '38-the-black-jewels.jpg': 'The Black Jewels',
      '39-old-kingdom.jpg': 'Old Kingdom',
      '40-the-queen-s-thief.jpg': "The Queen's Thief",
      '41-the-edge-chronicles.jpg': 'The Edge Chronicles',
      '42-the-bartimaeus-sequence.jpg': 'The Bartimaeus Sequence',
      '43-the-keys-to-the-kingdom.jpg': 'The Keys to the Kingdom',
      '44-the-mortal-instruments.jpg': 'The Mortal Instruments',
      '45-grishaverse.jpg': 'Grishaverse',
      '46-the-raven-cycle.jpg': 'The Raven Cycle',
      '47-the-books-of-pellinor.jpg': 'The Books of Pellinor',
      '48-the-demon-cycle.jpg': 'The Demon Cycle',
      '49-lightbringer.jpg': 'Lightbringer',
      '50-the-powder-mage-trilogy.jpg': 'The Powder Mage Trilogy',
      '51-the-gentleman-bastard-sequence.jpg': 'The Gentleman Bastard Sequence',
      '52-the-riyria-revelations.jpg': 'The Riyria Revelations',
      '53-the-books-of-babel.jpg': 'The Books of Babel',
      '54-the-licanius-trilogy.jpg': 'The Licanius Trilogy',
      '55-the-green-bone-saga.jpg': 'The Green Bone Saga',
      '56-the-locked-tomb.jpg': 'The Locked Tomb',
      '57-the-daevabad-trilogy.jpg': 'The Daevabad Trilogy',
      '58-temeraire.jpg': 'Temeraire',
      '59-the-winternight-trilogy.jpg': 'The Winternight Trilogy',
      '60-the-broken-empire.jpg': 'The Broken Empire',
      '61-the-faithful-and-the-fallen.jpg': 'The Faithful and the Fallen',
      '62-the-books-of-the-raksura.jpg': 'The Books of the Raksura',
      '63-the-craft-sequence.jpg': 'The Craft Sequence',
      '64-the-divine-cities.jpg': 'The Divine Cities',
      '65-the-tide-child.jpg': 'The Tide Child',
      '66-the-dandelion-dynasty.jpg': 'The Dandelion Dynasty',
      '67-the-burning.jpg': 'The Burning',
      '68-world-of-the-five-gods.jpg': 'World of the Five Gods',
      '69-wayward-children.jpg': 'Wayward Children',
    },
  },
  'stephen-king-novels': {
    title: 'Stephen King novels',
    category: 'books',
    description:
      'Stephen King novels and novella-length standalone books from Carrie through Never Flinch.',
    tags: ['books', 'horror', 'stephen king'],
    labels: true,
    itemLabels: {
      '01-carrie.jpg': 'Carrie',
      '02-salem-s-lot.jpg': "'Salem's Lot",
      '03-the-shining.jpg': 'The Shining',
      '04-rage.jpg': 'Rage',
      '05-the-stand.jpg': 'The Stand',
      '06-the-long-walk.jpg': 'The Long Walk',
      '07-the-dead-zone.jpg': 'The Dead Zone',
      '08-firestarter.jpg': 'Firestarter',
      '09-roadwork.jpg': 'Roadwork',
      '10-cujo.jpg': 'Cujo',
      '11-the-running-man.jpg': 'The Running Man',
      '12-the-gunslinger.jpg': 'The Gunslinger',
      '13-christine.jpg': 'Christine',
      '14-pet-sematary.jpg': 'Pet Sematary',
      '15-cycle-of-the-werewolf.jpg': 'Cycle of the Werewolf',
      '16-the-talisman.jpg': 'The Talisman',
      '17-thinner.jpg': 'Thinner',
      '18-it.jpg': 'It',
      '19-the-eyes-of-the-dragon.jpg': 'The Eyes of the Dragon',
      '20-the-drawing-of-the-three.jpg': 'The Drawing of the Three',
      '21-misery.jpg': 'Misery',
      '22-the-tommyknockers.jpg': 'The Tommyknockers',
      '23-the-dark-half.jpg': 'The Dark Half',
      '24-the-waste-lands.jpg': 'The Waste Lands',
      '25-needful-things.jpg': 'Needful Things',
      '26-gerald-s-game.jpg': "Gerald's Game",
      '27-dolores-claiborne.jpg': 'Dolores Claiborne',
      '28-insomnia.jpg': 'Insomnia',
      '29-rose-madder.jpg': 'Rose Madder',
      '30-the-green-mile.jpg': 'The Green Mile',
      '31-desperation.jpg': 'Desperation',
      '32-the-regulators.jpg': 'The Regulators',
      '33-wizard-and-glass.jpg': 'Wizard and Glass',
      '34-bag-of-bones.jpg': 'Bag of Bones',
      '35-the-girl-who-loved-tom-gordon.jpg': 'The Girl Who Loved Tom Gordon',
      '36-dreamcatcher.jpg': 'Dreamcatcher',
      '37-black-house.jpg': 'Black House',
      '38-from-a-buick-8.jpg': 'From a Buick 8',
      '39-wolves-of-the-calla.jpg': 'Wolves of the Calla',
      '40-song-of-susannah.jpg': 'Song of Susannah',
      '41-the-dark-tower.jpg': 'The Dark Tower',
      '42-the-colorado-kid.jpg': 'The Colorado Kid',
      '43-cell.jpg': 'Cell',
      '44-lisey-s-story.jpg': "Lisey's Story",
      '45-blaze.jpg': 'Blaze',
      '46-duma-key.jpg': 'Duma Key',
      '47-under-the-dome.jpg': 'Under the Dome',
      '48-11-22-63.jpg': '11/22/63',
      '49-the-wind-through-the-keyhole.jpg': 'The Wind Through the Keyhole',
      '50-joyland.jpg': 'Joyland',
      '51-doctor-sleep.jpg': 'Doctor Sleep',
      '52-mr-mercedes.jpg': 'Mr. Mercedes',
      '53-revival.jpg': 'Revival',
      '54-finders-keepers.jpg': 'Finders Keepers',
      '55-end-of-watch.jpg': 'End of Watch',
      '56-gwendy-s-button-box.jpg': "Gwendy's Button Box",
      '57-sleeping-beauties.jpg': 'Sleeping Beauties',
      '58-the-outsider.jpg': 'The Outsider',
      '59-elevation.jpg': 'Elevation',
      '60-the-institute.jpg': 'The Institute',
      '61-later.jpg': 'Later',
      '62-billy-summers.jpg': 'Billy Summers',
      '63-gwendy-s-final-task.jpg': "Gwendy's Final Task",
      '64-fairy-tale.jpg': 'Fairy Tale',
      '65-holly.jpg': 'Holly',
      '66-never-flinch.jpg': 'Never Flinch',
    },
  },
  'harry-potter-books': {
    title: 'Harry Potter books',
    category: 'books',
    description: 'The seven main Harry Potter novels in publication order.',
    tags: ['books', 'fantasy', 'harry potter'],
    labels: true,
    itemLabels: {
      '01-philosopher-s-stone.jpg': "Philosopher's Stone",
      '02-chamber-of-secrets.jpg': 'Chamber of Secrets',
      '03-prisoner-of-azkaban.jpg': 'Prisoner of Azkaban',
      '04-goblet-of-fire.jpg': 'Goblet of Fire',
      '05-order-of-the-phoenix.jpg': 'Order of the Phoenix',
      '06-half-blood-prince.jpg': 'Half-Blood Prince',
      '07-deathly-hallows.jpg': 'Deathly Hallows',
    },
  },
} satisfies Record<string, FolderMeta>
