// scripts/marketplace-seed/catalog/gaming.ts
// gaming example metadata for marketplace template seeds

import { SSBU_CLASSIC_PRESET } from '../constants'
import type { MarketplaceTemplateCriterion } from '@tierlistbuilder/contracts/marketplace/templateCriterion'
import type { FolderMeta } from '../types'

const SSBU_CRITERIA = [
  {
    externalId: 'competitive',
    name: 'Competitive',
    shortName: 'Comp',
    prompt: 'Rank fighters by competitive viability.',
    axisTop: 'Strongest',
    axisBottom: 'Weakest',
    order: 0,
    isPrimary: true,
    status: 'active',
  },
  {
    externalId: 'favorites',
    name: 'Favorites',
    shortName: 'Favs',
    prompt: 'Rank fighters by personal preference.',
    axisTop: 'Favorite',
    axisBottom: 'Least favorite',
    order: 1,
    isPrimary: false,
    status: 'active',
  },
  {
    externalId: 'fun',
    name: 'Fun',
    shortName: 'Fun',
    prompt: 'Rank fighters by how fun they are to play.',
    axisTop: 'Most fun',
    axisBottom: 'Least fun',
    order: 2,
    isPrimary: false,
    status: 'active',
  },
  {
    externalId: 'annoying',
    name: 'Annoying',
    shortName: 'Annoying',
    prompt: 'Rank fighters by how annoying they are to fight.',
    axisTop: 'Most annoying',
    axisBottom: 'Least annoying',
    order: 3,
    isPrimary: false,
    status: 'active',
  },
  {
    externalId: 'newcomer',
    name: 'Newcomer friendly',
    shortName: 'Newcomer',
    prompt: 'Rank fighters by how approachable they are for new players.',
    axisTop: 'Easiest to learn',
    axisBottom: 'Hardest to learn',
    order: 4,
    isPrimary: false,
    status: 'active',
  },
] satisfies readonly MarketplaceTemplateCriterion[]

// primary criterion externalId stays 'default' so previously seeded Zelda
// rankings (DEFAULT_TEMPLATE_CRITERION_EXTERNAL_ID) keep a valid lane ref
const ZELDA_CRITERIA = [
  {
    externalId: 'default',
    name: 'Overall',
    shortName: 'Overall',
    prompt: 'Rank Zelda games on overall quality + impact.',
    axisTop: 'Best',
    axisBottom: 'Worst',
    order: 0,
    isPrimary: true,
    status: 'active',
  },
  {
    externalId: 'favorites',
    name: 'Favorites',
    shortName: 'Favs',
    prompt: 'Rank Zelda games by personal love + replay value.',
    axisTop: 'All-time favorite',
    axisBottom: 'Skip',
    order: 1,
    isPrimary: false,
    status: 'active',
  },
  {
    externalId: 'dungeons',
    name: 'Dungeons',
    shortName: 'Dungeons',
    prompt: 'Rank Zelda games by dungeon design and puzzle spaces.',
    axisTop: 'Best dungeons',
    axisBottom: 'Weakest dungeons',
    order: 2,
    isPrimary: false,
    status: 'active',
  },
  {
    externalId: 'story',
    name: 'Story',
    shortName: 'Story',
    prompt: 'Rank Zelda games by story, atmosphere, and worldbuilding.',
    axisTop: 'Most memorable',
    axisBottom: 'Least memorable',
    order: 3,
    isPrimary: false,
    status: 'active',
  },
] satisfies readonly MarketplaceTemplateCriterion[]

export const GAMING_TEMPLATE_META = {
  'game-consoles': {
    title: 'Game consoles',
    category: 'gaming',
    description:
      'Landmark home consoles, handhelds, microconsoles, and PC handhelds across console generations.',
    tags: ['gaming', 'consoles', 'hardware'],
    labels: true,
    itemLabels: {
      '01-magnavox-odyssey.jpg': 'Magnavox Odyssey',
      '02-fairchild-channel-f.jpg': 'Fairchild Channel F',
      '03-atari-2600.png': 'Atari 2600',
      '04-magnavox-odyssey-2.jpg': 'Magnavox Odyssey 2',
      '05-intellivision.png': 'Intellivision',
      '06-colecovision.jpg': 'ColecoVision',
      '07-atari-5200.jpg': 'Atari 5200',
      '08-vectrex.jpg': 'Vectrex',
      '09-nes.png': 'NES',
      '10-sega-master-system.jpg': 'Sega Master System',
      '11-atari-7800.jpg': 'Atari 7800',
      '12-turbografx-16.jpg': 'TurboGrafx-16',
      '13-sega-genesis.jpg': 'Sega Genesis',
      '14-neo-geo.png': 'Neo Geo',
      '15-snes.png': 'SNES',
      '16-3do.jpg': '3DO',
      '17-atari-jaguar.jpg': 'Atari Jaguar',
      '18-sega-saturn.png': 'Sega Saturn',
      '19-playstation.jpg': 'PlayStation',
      '20-virtual-boy.png': 'Virtual Boy',
      '21-nintendo-64.jpg': 'Nintendo 64',
      '22-pc-fx.jpg': 'PC-FX',
      '23-dreamcast.jpg': 'Dreamcast',
      '24-playstation-2.png': 'PlayStation 2',
      '25-gamecube.png': 'GameCube',
      '26-xbox.jpg': 'Xbox',
      '27-xbox-360.png': 'Xbox 360',
      '28-playstation-3.jpg': 'PlayStation 3',
      '29-wii.png': 'Wii',
      '30-ouya.jpg': 'Ouya',
      '31-wii-u.png': 'Wii U',
      '32-playstation-4.jpg': 'PlayStation 4',
      '33-xbox-one.png': 'Xbox One',
      '34-nvidia-shield-tv.jpg': 'Nvidia Shield TV',
      '35-nintendo-switch.jpg': 'Nintendo Switch',
      '36-playstation-5.png': 'PlayStation 5',
      '37-xbox-series-x.png': 'Xbox Series X',
      '38-xbox-series-s.png': 'Xbox Series S',
      '39-nintendo-switch-2.png': 'Nintendo Switch 2',
      '40-game-and-watch.png': 'Game & Watch',
      '41-game-boy.png': 'Game Boy',
      '42-atari-lynx.jpg': 'Atari Lynx',
      '43-game-gear.png': 'Game Gear',
      '44-turboexpress.jpg': 'TurboExpress',
      '45-game-boy-color.png': 'Game Boy Color',
      '46-neo-geo-pocket-color.jpg': 'Neo Geo Pocket Color',
      '47-wonderswan-color.jpg': 'WonderSwan Color',
      '48-game-boy-advance.png': 'Game Boy Advance',
      '49-n-gage.png': 'N-Gage',
      '50-nintendo-ds.png': 'Nintendo DS',
      '51-psp.jpg': 'PSP',
      '52-nintendo-3ds.png': 'Nintendo 3DS',
      '53-playstation-vita.jpg': 'PlayStation Vita',
      '54-nintendo-switch-lite.jpg': 'Nintendo Switch Lite',
      '55-analogue-pocket.jpg': 'Analogue Pocket',
      '56-playdate.png': 'Playdate',
      '57-steam-deck.png': 'Steam Deck',
      '58-asus-rog-ally.jpg': 'ASUS ROG Ally',
      '59-lenovo-legion-go.jpg': 'Lenovo Legion Go',
      '60-msi-claw.png': 'MSI Claw',
    },
  },
  'final-fantasy-mainline': {
    title: 'Final Fantasy mainline series',
    category: 'gaming',
    description:
      'Every numbered Final Fantasy game from FF I through XVI, in release order.',
    tags: ['rpg', 'final fantasy', 'square enix'],
  },
  'mario-kart-8-deluxe': {
    title: 'Mario Kart 8 Deluxe roster',
    category: 'gaming',
    description:
      'All 48 racers from Mario Kart 8 Deluxe, including DLC characters.',
    tags: ['nintendo', 'racing', 'mario kart'],
  },
  'mortal-kombat-1': {
    title: 'Mortal Kombat 1 roster',
    category: 'gaming',
    description: 'The base + Kombat Pack roster from Mortal Kombat 1 (2023).',
    tags: ['fighting', 'mortal kombat', 'netherrealm'],
  },
  'pokemon-generations': {
    title: 'Pokemon game generations',
    category: 'gaming',
    description:
      'Mainline Pokemon generations represented by paired flagship games, including the announced tenth generation.',
    tags: ['pokemon', 'nintendo', 'generations'],
    labels: true,
    itemLabels: {
      '01-generation-i-red-blue-yellow.webp':
        'Generation I: Red, Blue & Yellow',
      '02-generation-ii-gold-silver.png': 'Generation II: Gold & Silver',
      '03-generation-iii-ruby-sapphire.jpg': 'Generation III: Ruby & Sapphire',
      '04-generation-iv-diamond-pearl.jpg': 'Generation IV: Diamond & Pearl',
      '05-generation-v-black-white.jpg': 'Generation V: Black & White',
      '06-generation-vi-x-y.jpg': 'Generation VI: X & Y',
      '07-generation-vii-sun-moon.jpg': 'Generation VII: Sun & Moon',
      '08-generation-viii-sword-shield.jpg': 'Generation VIII: Sword & Shield',
      '09-generation-ix-scarlet-violet.png': 'Generation IX: Scarlet & Violet',
      '10-generation-x-winds-waves.png': 'Generation X: Winds & Waves',
    },
  },
  'pokemon-starters': {
    title: 'Pokémon starter trios',
    category: 'gaming',
    description: 'The first-stage starters from every mainline generation.',
    tags: ['pokemon', 'starters', 'nintendo'],
  },
  'ssbu-fighters': {
    title: 'Super Smash Bros. Ultimate roster',
    category: 'gaming',
    description: 'All 87 fighters in Super Smash Bros. Ultimate, base + DLC.',
    tags: ['nintendo', 'fighting', 'smash bros'],
    coverImage: 'covers/ssbu-fighters.jpg',
    // banner art is panoramic (~5.4:1); zoom out a notch so character heads
    // aren't clipped, but stay tight enough that the matte stays a thin band
    coverZoom: 1.5,
    suggestedTiers: SSBU_CLASSIC_PRESET,
    criteria: SSBU_CRITERIA,
  },
  'street-fighter-6': {
    title: 'Street Fighter 6 roster',
    category: 'gaming',
    description: 'Base + Year 1 + Year 2 fighters from Street Fighter 6.',
    tags: ['fighting', 'capcom', 'street fighter'],
  },
  'zelda-games': {
    title: 'Legend of Zelda mainline',
    category: 'gaming',
    description: 'Every mainline Zelda title, by box art.',
    tags: ['zelda', 'nintendo', 'rpg'],
    coverImage: 'covers/zelda-games.jpg',
    criteria: ZELDA_CRITERIA,
  },
  'nintendo-franchises': {
    title: 'Nintendo franchises',
    category: 'gaming',
    description:
      "Nintendo's biggest franchises — Mario, Zelda, Pokémon, Smash, Fire Emblem, & a deep bench of platformers, party games, & quirky sub-series.",
    tags: ['nintendo', 'franchises', 'gaming', 'logos'],
    labels: true,
    itemLabels: {
      '002-the-legend-of-zelda.png': 'The Legend of Zelda',
      '003-pokemon.png': 'Pokémon',
      '008-f-zero.png': 'F-Zero',
      '015-super-smash-bros.png': 'Super Smash Bros.',
      '018-warioware.png': 'WarioWare',
      '020-punch-out.png': 'Punch-Out!!',
      '024-arms.png': 'ARMS',
      '025-game-and-watch.png': 'Game & Watch',
    },
  },
} satisfies Record<string, FolderMeta>
