// scripts/marketplace-seed/catalog/moviesTv.ts
// TV metadata for marketplace template seeds

import type { FolderMeta } from '../types'

export const MOVIES_TV_TEMPLATE_META = {
  'prestige-tv-dramas': {
    title: 'Prestige TV dramas',
    category: 'movies',
    description:
      'Landmark prestige dramas, dramatic anthologies, and limited series across HBO, AMC, FX, broadcast, and streaming eras.',
    tags: ['tv', 'drama', 'prestige tv', 'series'],
    labels: true,
    itemLabels: {
      '017-the-handmaids-tale.jpg': "The Handmaid's Tale",
      '028-the-x-files.jpg': 'The X-Files',
      '029-battlestar-galactica-2003.jpg': 'Battlestar Galactica (2003)',
      '031-mr-robot.jpg': 'Mr. Robot',
      '054-shogun.jpg': 'Shōgun',
      '058-the-queens-gambit.jpg': "The Queen's Gambit",
    },
  },
  sitcoms: {
    title: 'Sitcoms',
    category: 'movies',
    description:
      'Classic and modern sitcoms across broadcast, cable, streaming, UK, Irish, and Canadian television.',
    tags: ['tv', 'sitcoms', 'comedy', 'series'],
    labels: true,
    itemLabels: {
      '001-i-love-lucy.jpg': 'I Love Lucy',
      '002-the-honeymooners.jpg': 'The Honeymooners',
      '003-leave-it-to-beaver.jpg': 'Leave It to Beaver',
      '004-the-andy-griffith-show.jpg': 'The Andy Griffith Show',
      '005-my-three-sons.jpg': 'My Three Sons',
      '006-the-dick-van-dyke-show.jpg': 'The Dick Van Dyke Show',
      '007-the-addams-family.jpg': 'The Addams Family',
      '008-the-munsters.jpg': 'The Munsters',
      '009-gilligans-island.jpg': "Gilligan's Island",
      '010-bewitched.jpg': 'Bewitched',
      '011-get-smart.jpg': 'Get Smart',
      '012-i-dream-of-jeannie.jpg': 'I Dream of Jeannie',
      '013-the-brady-bunch.jpg': 'The Brady Bunch',
      '014-the-odd-couple.jpg': 'The Odd Couple',
      '015-the-mary-tyler-moore-show.jpg': 'The Mary Tyler Moore Show',
      '016-all-in-the-family.jpg': 'All in the Family',
      '017-sanford-and-son.jpg': 'Sanford and Son',
      '018-maude.jpg': 'Maude',
      '019-the-bob-newhart-show.jpg': 'The Bob Newhart Show',
      '020-mash.jpg': 'M*A*S*H',
      '021-good-times.jpg': 'Good Times',
      '022-happy-days.jpg': 'Happy Days',
      '023-the-jeffersons.jpg': 'The Jeffersons',
      '024-fawlty-towers.jpg': 'Fawlty Towers',
      '025-one-day-at-a-time-1975.jpg': 'One Day at a Time (1975)',
      '026-barney-miller.jpg': 'Barney Miller',
      '027-laverne-and-shirley.jpg': 'Laverne & Shirley',
      '028-alice.jpg': 'Alice',
      '029-threes-company.jpg': "Three's Company",
      '030-soap.jpg': 'Soap',
      '031-taxi.jpg': 'Taxi',
      '032-mork-and-mindy.jpg': 'Mork & Mindy',
      '033-wkrp-in-cincinnati.jpg': 'WKRP in Cincinnati',
      '034-diffrent-strokes.jpg': "Diff'rent Strokes",
      '035-the-facts-of-life.jpg': 'The Facts of Life',
      '036-benson.jpg': 'Benson',
      '037-only-fools-and-horses.jpg': 'Only Fools and Horses',
      '038-cheers.jpg': 'Cheers',
      '039-family-ties.jpg': 'Family Ties',
      '040-blackadder.jpg': 'Blackadder',
      '041-night-court.jpg': 'Night Court',
      '042-the-cosby-show.jpg': 'The Cosby Show',
      '043-the-golden-girls.jpg': 'The Golden Girls',
      '044-alf.jpg': 'ALF',
      '045-designing-women.jpg': 'Designing Women',
      '046-married-with-children.jpg': 'Married... with Children',
      '047-full-house.jpg': 'Full House',
      '048-a-different-world.jpg': 'A Different World',
      '049-roseanne.jpg': 'Roseanne',
      '050-red-dwarf.jpg': 'Red Dwarf',
      '051-murphy-brown.jpg': 'Murphy Brown',
      '052-the-wonder-years.jpg': 'The Wonder Years',
      '053-saved-by-the-bell.jpg': 'Saved by the Bell',
      '054-seinfeld.jpg': 'Seinfeld',
      '055-the-fresh-prince-of-bel-air.jpg': 'The Fresh Prince of Bel-Air',
      '056-mr-bean.jpg': 'Mr. Bean',
      '057-keeping-up-appearances.jpg': 'Keeping Up Appearances',
      '058-home-improvement.jpg': 'Home Improvement',
      '059-mad-about-you.jpg': 'Mad About You',
      '060-the-larry-sanders-show.jpg': 'The Larry Sanders Show',
      '061-martin.jpg': 'Martin',
      '062-absolutely-fabulous.jpg': 'Absolutely Fabulous',
      '063-frasier.jpg': 'Frasier',
      '064-living-single.jpg': 'Living Single',
      '065-the-nanny.jpg': 'The Nanny',
      '066-friends.jpg': 'Friends',
      '067-the-vicar-of-dibley.jpg': 'The Vicar of Dibley',
      '068-father-ted.jpg': 'Father Ted',
      '069-newsradio.jpg': 'NewsRadio',
      '070-moesha.jpg': 'Moesha',
      '071-3rd-rock-from-the-sun.jpg': '3rd Rock from the Sun',
      '072-sabrina-the-teenage-witch.jpg': 'Sabrina the Teenage Witch',
      '073-spin-city.jpg': 'Spin City',
      '074-everybody-loves-raymond.jpg': 'Everybody Loves Raymond',
      '075-the-king-of-queens.jpg': 'The King of Queens',
      '076-will-and-grace.jpg': 'Will & Grace',
      '077-that-70s-show.jpg': "That '70s Show",
      '078-spaced.jpg': 'Spaced',
      '079-the-parkers.jpg': 'The Parkers',
      '080-malcolm-in-the-middle.jpg': 'Malcolm in the Middle',
      '081-girlfriends.jpg': 'Girlfriends',
      '082-curb-your-enthusiasm.jpg': 'Curb Your Enthusiasm',
      '083-scrubs.jpg': 'Scrubs',
      '084-my-wife-and-kids.jpg': 'My Wife and Kids',
      '085-the-bernie-mac-show.jpg': 'The Bernie Mac Show',
      '086-trailer-park-boys.jpg': 'Trailer Park Boys',
      '087-still-game.jpg': 'Still Game',
      '088-peep-show.jpg': 'Peep Show',
      '089-reno-911.jpg': 'Reno 911!',
      '090-arrested-development.jpg': 'Arrested Development',
      '091-two-and-a-half-men.jpg': 'Two and a Half Men',
      '092-the-office-uk.jpg': 'The Office (UK)',
      '093-extras.jpg': 'Extras',
      '094-the-thick-of-it.jpg': 'The Thick of It',
      '095-the-office-us.jpg': 'The Office (US)',
      '096-how-i-met-your-mother.jpg': 'How I Met Your Mother',
      '097-its-always-sunny-in-philadelphia.jpg':
        "It's Always Sunny in Philadelphia",
      '098-everybody-hates-chris.jpg': 'Everybody Hates Chris',
      '099-my-name-is-earl.jpg': 'My Name Is Earl',
      '100-the-it-crowd.jpg': 'The IT Crowd',
      '101-the-new-adventures-of-old-christine.jpg':
        'The New Adventures of Old Christine',
      '102-30-rock.jpg': '30 Rock',
      '103-gavin-and-stacey.jpg': 'Gavin & Stacey',
      '104-rules-of-engagement.jpg': 'Rules of Engagement',
      '105-the-big-bang-theory.jpg': 'The Big Bang Theory',
      '106-outnumbered.jpg': 'Outnumbered',
      '107-the-inbetweeners.jpg': 'The Inbetweeners',
      '108-better-off-ted.jpg': 'Better Off Ted',
      '109-party-down.jpg': 'Party Down',
      '110-parks-and-recreation.jpg': 'Parks and Recreation',
      '111-community.jpg': 'Community',
      '112-cougar-town.jpg': 'Cougar Town',
      '113-modern-family.jpg': 'Modern Family',
      '114-the-middle.jpg': 'The Middle',
      '115-miranda.jpg': 'Miranda',
      '116-happy-endings.jpg': 'Happy Endings',
      '117-workaholics.jpg': 'Workaholics',
      '118-2-broke-girls.jpg': '2 Broke Girls',
      '119-new-girl.jpg': 'New Girl',
      '120-veep.jpg': 'Veep',
      '121-the-mindy-project.jpg': 'The Mindy Project',
      '122-brooklyn-nine-nine.jpg': 'Brooklyn Nine-Nine',
      '123-mom.jpg': 'Mom',
      '124-the-goldbergs.jpg': 'The Goldbergs',
      '125-broad-city.jpg': 'Broad City',
      '126-detectorists.jpg': 'Detectorists',
      '127-silicon-valley.jpg': 'Silicon Valley',
      '128-schitts-creek.jpg': "Schitt's Creek",
      '129-black-ish.jpg': 'Black-ish',
      '130-fresh-off-the-boat.jpg': 'Fresh Off the Boat',
      '131-catastrophe.jpg': 'Catastrophe',
      '132-kims-convenience.jpg': "Kim's Convenience",
      '133-unbreakable-kimmy-schmidt.jpg': 'Unbreakable Kimmy Schmidt',
      '134-superstore.jpg': 'Superstore',
      '135-letterkenny.jpg': 'Letterkenny',
      '136-fleabag.jpg': 'Fleabag',
      '137-the-good-place.jpg': 'The Good Place',
      '138-one-day-at-a-time-2017.jpg': 'One Day at a Time (2017)',
      '139-this-country.jpg': 'This Country',
      '140-young-sheldon.jpg': 'Young Sheldon',
      '141-derry-girls.jpg': 'Derry Girls',
      '142-what-we-do-in-the-shadows.jpg': 'What We Do in the Shadows',
      '143-ghosts-uk.jpg': 'Ghosts (UK)',
      '144-ted-lasso.jpg': 'Ted Lasso',
      '145-ghosts-us.jpg': 'Ghosts (US)',
      '146-abbott-elementary.jpg': 'Abbott Elementary',
    },
  },
  'the-office-characters': {
    title: 'The Office characters',
    category: 'movies',
    description:
      'The Office (US) cast — Dunder Mifflin Scranton crew plus iconic recurring guests, bosses, & vendors across the saga.',
    tags: ['the office', 'tv', 'comedy', 'sitcom', 'characters'],
    labels: true,
    itemLabels: {
      '028-deangelo-vickers.webp': 'DeAngelo Vickers',
    },
  },
} satisfies Record<string, FolderMeta>
