// scripts/marketplace-seed/catalog/moviesMarvel.ts
// Marvel metadata for marketplace template seeds

import type { MarketplaceTemplateCriterion } from '@tierlistbuilder/contracts/marketplace/templateCriterion'
import type { FolderMeta } from '../types'

// primary criterion id stays 'default' so previously seeded MCU rankings
// (created when this template had only the implicit default criterion)
// keep a valid criterion reference after favorites is added
const MCU_CRITERIA = [
  {
    externalId: 'default',
    name: 'Overall',
    shortName: 'Overall',
    prompt: 'Rank MCU films on overall quality.',
    axisTop: 'Best',
    axisBottom: 'Worst',
    order: 0,
    isPrimary: true,
    status: 'active',
  },
  {
    externalId: 'favorites',
    name: 'Favorites',
    shortName: 'Favs',
    prompt: 'Rank MCU films by rewatch value + personal preference.',
    axisTop: 'Always rewatching',
    axisBottom: 'Skip',
    order: 1,
    isPrimary: false,
    status: 'active',
  },
] satisfies readonly MarketplaceTemplateCriterion[]

export const MOVIES_MARVEL_TEMPLATE_META = {
  'mcu-posters': {
    title: 'MCU films',
    category: 'movies',
    description:
      'Every theatrical Marvel Cinematic Universe release, by poster art.',
    tags: ['marvel', 'mcu', 'films'],
    criteria: MCU_CRITERIA,
  },
  'mcu-shows': {
    title: 'MCU streaming series',
    category: 'movies',
    description: 'Disney+ MCU shows from WandaVision onward.',
    tags: ['marvel', 'mcu', 'disney+'],
  },
  'mcu-characters': {
    title: 'MCU characters',
    category: 'movies',
    description:
      'MCU heroes, villains, allies, and supporting characters across films, Disney+ series, Specials, and legacy TV branches.',
    tags: ['marvel', 'mcu', 'characters', 'superheroes'],
    labels: true,
    itemLabels: {
      '007-spider-man.jpg': 'Spider-Man',
      '017-star-lord.png': 'Star-Lord',
      '026-ms-marvel.png': 'Ms. Marvel',
      '028-moon-knight.jpg': 'Moon Knight',
      '039-mbaku.jpg': "M'Baku",
      '045-iron-fist.jpg': 'Iron Fist',
      '052-america-chavez.jpg': 'America Chavez',
      '053-eros-starfox.jpg': 'Eros / Starfox',
      '054-layla-el-faouly.jpg': 'Layla El-Faouly',
      '057-agent-13-sharon-carter.jpg': 'Agent 13 / Sharon Carter',
      '059-riri-williams-ironheart.jpg': 'Riri Williams / Ironheart',
      '063-hunter-b-15.jpg': 'Hunter B-15',
      '098-wenwu-the-mandarin.jpg': 'Wenwu / The Mandarin',
      '103-kang-the-conqueror.jpg': 'Kang the Conqueror',
      '105-modok.jpg': 'M.O.D.O.K.',
      '114-black-order-ebony-maw.jpg': 'Ebony Maw',
      '115-black-order-proxima-midnight.jpg': 'Proxima Midnight',
      '116-black-order-corvus-glaive.jpg': 'Corvus Glaive',
      '117-black-order-cull-obsidian.jpg': 'Cull Obsidian',
      '123-john-walker-us-agent.jpg': 'John Walker / U.S. Agent',
      '124-karli-morgenthau.jpg': 'Karli Morgenthau',
      '127-the-leader.jpg': 'The Leader',
      '144-jarvis.jpg': 'J.A.R.V.I.S.',
      '145-friday.jpg': 'F.R.I.D.A.Y.',
      '148-tchaka.jpg': "T'Chaka",
      '151-thaddeus-ross.jpg': 'Thaddeus Ross / Red Hulk',
      '164-x-23.jpg': 'X-23',
      '169-silver-surfer-shalla-bal.jpg': 'Silver Surfer / Shalla-Bal',
      '173-valentina-allegra-de-fontaine.jpg': 'Valentina Allegra de Fontaine',
      '174-joaquin-torres-falcon.jpg': 'Joaquin Torres / Falcon',
      '180-wiccan.jpg': 'Billy Maximoff / Wiccan',
      '181-tommy-maximoff-speed.jpg': 'Tommy Maximoff / Speed',
      '182-death-rio-vidal.jpg': 'Death / Rio Vidal',
      '185-alice-wu-gulliver.jpg': 'Alice Wu-Gulliver',
      '190-baron-mordo.jpg': 'Baron Mordo',
      '194-the-collector.jpg': 'The Collector',
      '197-giah.jpg': "G'iah",
      '201-white-vision.jpg': 'White Vision',
      '202-obadiah-stane-iron-monger.jpg': 'Obadiah Stane / Iron Monger',
      '219-yo-yo-rodriguez.jpg': 'Yo-Yo Rodriguez',
      '220-ghost-rider-robbie-reyes.jpg': 'Ghost Rider / Robbie Reyes',
      '228-white-tiger.jpg': 'White Tiger / Hector Ayala',
    },
  },
  'mcu-heroes': {
    title: 'MCU heroes',
    category: 'movies',
    description:
      'Heroes, antiheroes, and allies of the Marvel Cinematic Universe.',
    tags: ['marvel', 'mcu', 'heroes', 'superheroes', 'avengers'],
    labels: true,
    itemLabels: {
      '007-spider-man.jpg': 'Spider-Man',
      '017-star-lord.png': 'Star-Lord',
      '026-ms-marvel.png': 'Ms. Marvel',
      '028-moon-knight.jpg': 'Moon Knight',
      '039-mbaku.jpg': "M'Baku",
      '044-iron-fist.jpg': 'Iron Fist',
      '049-america-chavez.jpg': 'America Chavez',
      '050-eros-starfox.jpg': 'Eros / Starfox',
      '051-layla-el-faouly.jpg': 'Layla El-Faouly',
      '053-agent-13-sharon-carter.jpg': 'Agent 13 / Sharon Carter',
      '054-riri-williams-ironheart.jpg': 'Riri Williams / Ironheart',
      '058-hunter-b-15.jpg': 'Hunter B-15',
      '075-john-walker-us-agent.jpg': 'John Walker / U.S. Agent',
      '087-x-23.jpg': 'X-23',
      '092-silver-surfer-shalla-bal.jpg': 'Silver Surfer / Shalla-Bal',
      '095-joaquin-torres-falcon.jpg': 'Joaquin Torres / Falcon',
      '099-wiccan.jpg': 'Billy Maximoff / Wiccan',
      '100-tommy-maximoff-speed.jpg': 'Tommy Maximoff / Speed',
      '101-death-rio-vidal.jpg': 'Death / Rio Vidal',
      '104-alice-wu-gulliver.jpg': 'Alice Wu-Gulliver',
      '109-baron-mordo.jpg': 'Baron Mordo',
      '114-giah.jpg': "G'iah",
      '115-white-vision.jpg': 'White Vision',
      '118-yo-yo-rodriguez.jpg': 'Yo-Yo Rodriguez',
      '119-ghost-rider-robbie-reyes.jpg': 'Ghost Rider / Robbie Reyes',
      '121-white-tiger.jpg': 'White Tiger / Hector Ayala',
    },
  },
  'mcu-villains': {
    title: 'MCU villains',
    category: 'movies',
    description:
      'Antagonists, big bads, and rogues of the Marvel Cinematic Universe.',
    tags: ['marvel', 'mcu', 'villains', 'supervillains'],
    labels: true,
    itemLabels: {
      '004-agent-13-sharon-carter.jpg': 'Agent 13 / Sharon Carter',
      '029-wenwu-the-mandarin.jpg': 'Wenwu / The Mandarin',
      '034-kang-the-conqueror.jpg': 'Kang the Conqueror',
      '036-modok.jpg': 'M.O.D.O.K.',
      '045-black-order-ebony-maw.jpg': 'Ebony Maw',
      '046-black-order-proxima-midnight.jpg': 'Proxima Midnight',
      '047-black-order-corvus-glaive.jpg': 'Corvus Glaive',
      '048-black-order-cull-obsidian.jpg': 'Cull Obsidian',
      '054-john-walker-us-agent.jpg': 'John Walker / U.S. Agent',
      '055-karli-morgenthau.jpg': 'Karli Morgenthau',
      '058-the-leader.jpg': 'The Leader',
      '063-silver-surfer-shalla-bal.jpg': 'Silver Surfer / Shalla-Bal',
      '067-valentina-allegra-de-fontaine.jpg': 'Valentina Allegra de Fontaine',
      '070-death-rio-vidal.jpg': 'Death / Rio Vidal',
      '071-baron-mordo.jpg': 'Baron Mordo',
      '074-obadiah-stane-iron-monger.jpg': 'Obadiah Stane / Iron Monger',
    },
  },
  'mcu-supporting-characters': {
    title: 'MCU supporting characters',
    category: 'movies',
    description:
      'Supporting cast of the Marvel Cinematic Universe — agents, family, friends, and allies without superhero identities.',
    tags: ['marvel', 'mcu', 'supporting', 'characters'],
    labels: true,
    itemLabels: {
      '019-jarvis.jpg': 'J.A.R.V.I.S.',
      '020-friday.jpg': 'F.R.I.D.A.Y.',
      '022-tchaka.jpg': "T'Chaka",
      '024-thaddeus-ross.jpg': 'Thaddeus Ross',
      '030-the-collector.jpg': 'The Collector',
    },
  },
} satisfies Record<string, FolderMeta>
