// scripts/marketplace-seed/catalog/techDev.ts
// developer-tech metadata for marketplace template seeds

import type { FolderMeta } from '../types'

export const TECH_DEV_TEMPLATE_META = {
  'programming-languages': {
    title: 'Programming languages',
    category: 'tech',
    description:
      'Widely used programming, scripting, markup, query, and shell languages.',
    tags: ['programming', 'software', 'languages'],
    labels: true,
    itemLabels: {
      '01-python.png': 'Python',
      '02-javascript.png': 'JavaScript',
      '03-typescript.png': 'TypeScript',
      '04-java.png': 'Java',
      '05-c.png': 'C',
      '06-cplusplus.png': 'C++',
      '07-csharp.png': 'C#',
      '08-go.png': 'Go',
      '09-rust.png': 'Rust',
      '10-kotlin.png': 'Kotlin',
      '11-swift.png': 'Swift',
      '12-php.png': 'PHP',
      '13-ruby.png': 'Ruby',
      '14-r.png': 'R',
      '15-julia.png': 'Julia',
      '16-scala.png': 'Scala',
      '17-haskell.png': 'Haskell',
      '18-elixir.png': 'Elixir',
      '19-erlang.png': 'Erlang',
      '20-perl.png': 'Perl',
      '21-lua.png': 'Lua',
      '22-dart.png': 'Dart',
      '23-objective-c.png': 'Objective-C',
      '24-matlab.png': 'MATLAB',
      '25-visual-basic-net.png': 'Visual Basic .NET',
      '26-bash.png': 'Bash',
      '27-powershell.png': 'PowerShell',
      '28-html.png': 'HTML',
      '29-css.png': 'CSS',
      '30-sql.png': 'SQL',
      '31-clojure.png': 'Clojure',
      '32-groovy.png': 'Groovy',
      '33-fsharp.png': 'F#',
      '34-fortran.png': 'Fortran',
      '35-cobol.png': 'COBOL',
      '36-solidity.png': 'Solidity',
      '37-zig.png': 'Zig',
      '38-nim.png': 'Nim',
      '39-crystal.png': 'Crystal',
      '40-ocaml.png': 'OCaml',
      '41-elm.png': 'Elm',
      '42-graphql.png': 'GraphQL',
      '43-markdown.png': 'Markdown',
      '44-yaml.png': 'YAML',
      '45-json.png': 'JSON',
      '46-xml.png': 'XML',
      '47-delphi.png': 'Delphi',
      '48-latex.png': 'LaTeX',
      '49-apl.png': 'APL',
      '50-ballerina.png': 'Ballerina',
    },
  },
  'javascript-frameworks': {
    title: 'JavaScript frameworks',
    category: 'tech',
    description:
      'Frontend frameworks, meta-frameworks, and UI libraries used across modern JavaScript apps.',
    tags: ['javascript', 'frontend', 'frameworks'],
    labels: true,
    itemLabels: {
      '01-react.png': 'React',
      '02-vue.png': 'Vue',
      '03-angular.png': 'Angular',
      '04-svelte.png': 'Svelte',
      '05-next-js.png': 'Next.js',
      '06-nuxt.png': 'Nuxt',
      '07-remix.png': 'Remix',
      '08-astro.png': 'Astro',
      '09-solid.png': 'Solid',
      '10-ember-js.png': 'Ember.js',
      '11-preact.png': 'Preact',
      '12-qwik.png': 'Qwik',
      '13-alpine-js.png': 'Alpine.js',
    },
  },
  databases: {
    title: 'Databases',
    category: 'tech',
    description:
      'Relational, document, key-value, graph, search, and analytics databases.',
    tags: ['databases', 'backend', 'data'],
    labels: true,
    itemLabels: {
      '01-postgresql.png': 'PostgreSQL',
      '02-mysql.png': 'MySQL',
      '03-sqlite.png': 'SQLite',
      '04-mongodb.png': 'MongoDB',
      '05-redis.png': 'Redis',
      '06-apache-cassandra.png': 'Apache Cassandra',
      '07-elasticsearch.png': 'Elasticsearch',
      '08-amazon-dynamodb.png': 'Amazon DynamoDB',
      '09-snowflake.png': 'Snowflake',
      '10-clickhouse.png': 'ClickHouse',
      '11-neo4j.png': 'Neo4j',
      '12-oracle-database.png': 'Oracle Database',
      '13-microsoft-sql-server.png': 'Microsoft SQL Server',
      '14-supabase.png': 'Supabase',
    },
  },
  'cloud-platforms': {
    title: 'Cloud platforms',
    category: 'tech',
    description:
      'Cloud providers, app platforms, edge networks, and developer hosting services.',
    tags: ['cloud', 'hosting', 'platforms'],
    labels: true,
    itemLabels: {
      '01-amazon-web-services.png': 'Amazon Web Services',
      '02-microsoft-azure.png': 'Microsoft Azure',
      '03-google-cloud.png': 'Google Cloud',
      '04-cloudflare.png': 'Cloudflare',
      '05-vercel.png': 'Vercel',
      '06-netlify.png': 'Netlify',
      '07-heroku.png': 'Heroku',
      '08-digitalocean.png': 'DigitalOcean',
      '09-firebase.png': 'Firebase',
      '10-supabase.png': 'Supabase',
      '11-render.png': 'Render',
      '12-railway.png': 'Railway',
      '13-fly-io.png': 'Fly.io',
    },
  },
} satisfies Record<string, FolderMeta>
